### ISSUE TITLE
What does this line mean? Why None?

### ISSUE THREAD

**Issue by guotong1988** [xiaojunxu/SQLNet#10]
`torch.autograd.backward(cond_score[1], [None for _ in cond_score[1]])`

https://github.com/xiaojunxu/SQLNet/blob/master/sqlnet/model/seq2sql.py#L197

@xiaojunxu Thank you!

**Comment by xiaojunxu** [comment]
This is a standard PyTorch reinforcement learning implementation. You may refer to [here](https://discuss.pytorch.org/t/what-is-action-reinforce-r-doing-actually/1294).

**Comment by guotong1988** [comment]
Thank you very much
