### ISSUE TITLE
Ressources and runtimes

### ISSUE THREAD

**Issue by sbBlank** [xiaojunxu/SQLNet#11]
Hi,

I was wondering whether you could give some informations about the resources you used and which runtimes you achieved.
- How many and what kind of GPUs did you use?
- What runtimes did you obtain for the normal dataset and for the toy-dataset (for debugging)?

Best regards,
Sebastian

**Comment by xiaojunxu** [comment]
We use one GeForce GTX 1080. For `python train.py --ca`, it takes around 12 min per epoch.
