### ISSUE TITLE
What does max_tok_num mean?

### ISSUE THREAD

**Issue by guotong1988** [xiaojunxu/SQLNet#4]
https://github.com/xxj96/SQLNet/blob/master/sqlnet/model/sqlnet.py#L25

To the best of my knowledge, I guess `self.max_tok_num` is more like a hidden dim and is not the max token number.

Thank you @xxj96

**Comment by xxj96** [comment]
'max_tok_num' denotes the upper bound of the number of input tokens. This is used in the pointer network when predicting the values of WHERE clauses. I have to set an upper bound for input tokens because the output of the pointer network is a probability vector over all input tokens, indicating which input token is selected.

**Comment by guotong1988** [comment]
Thank you ！

I could understand other places, except this place where `self.max_tok_num` appears.

https://github.com/xiaojunxu/SQLNet/blob/master/sqlnet/model/modules/sqlnet_condition_predict.py#L65

```
self.cond_str_decoder = nn.LSTM(input_size=self.max_tok_num,
                hidden_size=N_h, num_layers=N_depth,
                batch_first=True, dropout=0.3)
```

**Comment by xiaojunxu** [comment]
The input of the decoding network is also a one-hot representation indicating which token the current input is. For example, if the encoded sequence is 'How many people are there' and the latest generated token is 'many', then the input of decoder is [0, 1, 0, 0, 0] (not the word embedding of 'many').

**Comment by guotong1988** [comment]
What does "the latest generated token" mean?
Thank you very much.
Sorry to trouble you.

**Comment by xiaojunxu** [comment]
A Seq2Seq model generates a sentence token by token. If the model is going to generate sentence 'A lot of apples' and the current generated one is 'a lot', then in the next step, 'the latest generated token' is 'lot'.
