### ISSUE TITLE
What does the code mean?

### ISSUE THREAD

**Issue by zenghsh3** [xiaojunxu/SQLNet#6]
https://github.com/xiaojunxu/SQLNet/blob/533ac0d8e77cb3751b0c80dbac23f845c4a20334/sqlnet/model/modules/seq2sql_condition_predict.py#L86

I'm so sorry to trouble you, but I really can not understand the logic of that code.

Thank you @xxj96

**Comment by xiaojunxu** [comment]
Oh, thanks for the issue and I fixed the typo. The first condition should be 'len(done_set) < B', indicating whether all the cases in the batch has seen the <END> symbol. The second condition is the max length of the generated sentence (to prevent a sentence of infinite length).

**Comment by zenghsh3** [comment]
Make sense, thanks for your answer.
