### ISSUE TITLE
ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by xiaxia179** [xiaojunxu/SQLNet#7]
Traceback (most recent call last):
  File "extract_vocab.py", line 62, in <module>
    emb_array = np.stack(embs, axis=0)
  File "C:\python\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 347, in stack
    raise ValueError('all input arrays must have the same shape')

OS：windows10 64bit
python:3.6.1
cmd:python extract_vocab.py

**Comment by xiaojunxu** [comment]
Would you try to use python2.7? Not sure what problem will happen under python3.

**Comment by xiaxia179** [comment]
python2.7 + ubuntu is OK!

I just want to use python3 to run it！
