### ISSUE TITLE
Why the variable 'col_inp_var' is not used?

### ISSUE THREAD

**Issue by zenghsh3** [xiaojunxu/SQLNet#8]
https://github.com/xiaojunxu/SQLNet/blob/8997542839ba5815300f088d28bdb6b5f7613136/sqlnet/model/modules/seq2sql_condition_predict.py#L52

Sorry to trouble you again, but I think the embedding of columns should be used to encode the hidden state.

Thank you @xxj96

**Comment by xiaojunxu** [comment]
You may refer to equation (2) in the [Seq2SQL paper](https://arxiv.org/pdf/1709.00103.pdf).

**Comment by zenghsh3** [comment]
Oh, sorry, 'x_emb_var' has included the embedding of columns. (But it may be unnecessary for the aggregator predict, I think only question input is needed.)
